const SUPABASE_URL='https://bhpscrmwsmcwmvapemxz.supabase.co';const SUPABASE_KEY='sb_publishable_lj2RFmTiDKIMr7K-suRbCA_yOuLekl9';let db,user,profile;
const $=s=>document.querySelector(s);const $$=s=>document.querySelectorAll(s);const esc=v=>String(v??'').replace(/[&<>\\\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\\"':'&quot;',"'":'&#039;'}[c]));
async function init(){db=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);const {data:{user:u}}=await db.auth.getUser();user=u;if(!user){location.href='login.html';return}const {data:p,error}=await db.from('profiles').select('full_name,phone,role').eq('id',user.id).single();if(error||!p||!['admin','agent'].includes(p.role)){await db.auth.signOut();location.href='login.html';return}profile=p;$('#userInfo').textContent=`${p.full_name||user.email} · ${p.role==='admin'?'Administrateur':'Personnel'}`;if(p.role!=='admin'){$('#staffNav').style.display='none';$('#staff').innerHTML='<div class="panel"><h2>Accès restreint</h2><p>La gestion des comptes du personnel est réservée aux administrateurs.</p></div>';}setupNav();await loadAll();await loadDocuments()}
function setupNav(){$$('nav button').forEach(btn=>btn.onclick=()=>{$$('.view').forEach(v=>v.classList.remove('active'));$('#'+btn.dataset.view).classList.add('active');$('#pageTitle').textContent=btn.textContent;loadView(btn.dataset.view)});$('#logout').onclick=async()=>{await db.auth.signOut();location.href='login.html'};$('#refresh').onclick=loadAll;$('#staffForm')?.addEventListener('submit',createStaff);$('#documentForm')?.addEventListener('submit',uploadDocument)}
async function getRegs(){const {data,error}=await db.from('travel_registrations').select('*').order('created_at',{ascending:false});if(error){console.error(error);return []}return data||[]}
async function loadAll(){const r=await getRegs();renderStats(r);renderRecent(r);renderRegistrations(r);renderClients(r);renderStatsDetail(r);fillRegistrationSelect(r);if(profile.role==='admin')loadStaff()}
async function loadView(v){if(v==='dashboard'||v==='registrations'||v==='clients'||v==='stats')return loadAll();if(v==='payments')loadPayments();if(v==='documents')loadDocuments()}
function renderStats(r){$('#total').textContent=r.length;$('#newCount').textContent=r.filter(x=>x.status==='nouveau').length;$('#confirmed').textContent=r.filter(x=>x.status==='confirme').length;$('#cancelled').textContent=r.filter(x=>x.status==='annule').length}
function statusOptions(current){return ['nouveau','en_cours','confirme','annule'].map(s=>`<option ${s===current?'selected':''} value="${s}">${s.replace('_',' ')}</option>`).join('')}
function renderRegistrations(r){$('#registrationRows').innerHTML=r.map(x=>`<tr><td><strong>${esc(x.dossier_number)}</strong></td><td>${esc(x.full_name)}</td><td>${esc(x.service)}</td><td>${esc(x.phone)}</td><td>${esc(x.travel_date||'—')}</td><td><select class="status-select" data-id="${x.id}">${statusOptions(x.status)}</select></td><td><button class="small" data-detail="${x.id}">Voir</button></td></tr>`).join('')||'<tr><td colspan="7">Aucun dossier.</td></tr>';$$('.status-select').forEach(s=>s.onchange=async e=>{await db.from('travel_registrations').update({status:e.target.value}).eq('id',e.target.dataset.id);loadAll()})}
function renderRecent(r){$('#recent').innerHTML=r.slice(0,5).map(x=>`<div class="recent-row"><strong>${esc(x.dossier_number)}</strong><span>${esc(x.full_name)} · ${esc(x.service)}</span><span class="badge">${esc(x.status)}</span></div>`).join('')||'<p>Aucun dossier.</p>'}
function renderClients(r){$('#clientRows').innerHTML=r.map(x=>`<tr><td>${esc(x.full_name)}</td><td>${esc(x.phone)}</td><td>${esc(x.email||'—')}</td><td>${esc(x.service)}</td><td>${esc(x.dossier_number)}</td></tr>`).join('')||'<tr><td colspan="5">Aucun client.</td></tr>'}
function renderStatsDetail(r){$('#hajjCount').textContent=r.filter(x=>x.service==='hajj').length;$('#omraCount').textContent=r.filter(x=>x.service==='omra').length;$('#voyageCount').textContent=r.filter(x=>x.service==='voyage').length}
function fillRegistrationSelect(r){const s=$('#documentRegistration'),m=$('#documentMessage'),b=$('#documentForm button[type="submit"]');if(!s)return;if(!r.length){s.innerHTML='<option value="">Aucun dossier disponible</option>';s.disabled=true;if(b)b.disabled=true;if(m)m.textContent='Aucun dossier client n’est encore enregistré. Faites d’abord une inscription depuis le site public.';return}s.disabled=false;if(b)b.disabled=false;s.innerHTML='<option value="">Choisir un dossier</option>'+r.map(x=>`<option value="${x.id}">${esc(x.dossier_number)} — ${esc(x.full_name)}</option>`).join('');if(m&&m.textContent.startsWith('Aucun dossier'))m.textContent=''}
async function loadStaff(){const {data,error}=await db.from('profiles').select('full_name,phone,role,id').in('role',['admin','agent']).order('created_at',{ascending:false});if(error){$('#staffRows').innerHTML='<tr><td colspan="4">Impossible de charger le personnel.</td></tr>';return}$('#staffCount').textContent=(data||[]).length;$('#staffRows').innerHTML=(data||[]).map(x=>`<tr><td>${esc(x.full_name)}</td><td>Compte Supabase</td><td>${esc(x.phone||'—')}</td><td><span class="badge">${esc(x.role)}</span></td></tr>`).join('')||'<tr><td colspan="4">Aucun compte.</td></tr>'}
async function createStaff(e){e.preventDefault();if(profile.role!=='admin')return;const f=e.currentTarget,m=$('#staffMessage'),b=f.querySelector('button');b.disabled=true;b.textContent='Création...';const body={email:f.email.value.trim(),password:f.password.value,full_name:f.full_name.value.trim(),phone:f.phone.value.trim(),role:f.role.value};const {data:{session}}=await db.auth.getSession();const res=await fetch(`${SUPABASE_URL}/functions/v1/create-staff-user`,{method:'POST',headers:{Authorization:`Bearer ${session.access_token}`,'Content-Type':'application/json'},body:JSON.stringify(body)});const out=await res.json();b.disabled=false;b.textContent='Créer le compte';if(!res.ok){m.textContent=out.error||'Création impossible';return}m.textContent='Compte créé avec succès.';f.reset();loadStaff()}
async function uploadDocument(e){e.preventDefault();const f=e.currentTarget,m=$('#documentMessage'),b=f.querySelector('button'),file=$('#documentFile').files[0],registrationId=f.registration_id.value,type=f.document_type.value;if(!file||!registrationId||!type)return;if(file.size>10*1024*1024){m.textContent='Fichier trop volumineux : maximum 10 Mo.';return}const allowed=['application/pdf','image/jpeg','image/png','image/webp'];if(!allowed.includes(file.type)){m.textContent='Format non autorisé.';return}b.disabled=true;b.textContent='Téléversement...';m.textContent='';const path=`${registrationId}/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;const {error:up}=await db.storage.from('travel-documents').upload(path,file,{contentType:file.type,upsert:false});if(up){m.textContent='Échec du téléversement : '+up.message;b.disabled=false;b.textContent='Téléverser';return}const {error:meta}=await db.from('travel_documents').insert({travel_registration_id:registrationId,document_type:type,file_name:file.name,storage_path:path,status:'recu'});if(meta){await db.storage.from('travel-documents').remove([path]);m.textContent='Impossible d’enregistrer le document.';}else{m.textContent='Document téléversé et sécurisé.';f.reset();await loadDocuments()}b.disabled=false;b.textContent='Téléverser'}
async function loadDocuments(){const box=$('#documentList');if(!box)return;const {data,error}=await db.from('travel_documents').select('id,travel_registration_id,document_type,file_name,status,storage_path,uploaded_at,travel_registrations(dossier_number,full_name)').order('uploaded_at',{ascending:false});if(error){box.textContent='Impossible de charger les documents.';return}box.innerHTML=(data||[]).map(d=>`<div class="recent-row"><div><strong>${esc(d.file_name)}</strong><br><span class="muted">${esc(d.document_type)} · ${esc(d.travel_registrations?.dossier_number||'')}</span></div><span class="badge">${esc(d.status)}</span><button class="small" data-doc="${d.id}">Ouvrir</button></div>`).join('')||'<p>Aucun document.</p>';box.querySelectorAll('[data-doc]').forEach(btn=>btn.onclick=async()=>{const d=data.find(x=>String(x.id)===btn.dataset.doc);if(!d?.storage_path)return;const {data:signed,error:e}=await db.storage.from('travel-documents').createSignedUrl(d.storage_path,300);if(e){alert('Accès au document impossible.');return}window.open(signed.signedUrl,'_blank','noopener')})}
async function loadPayments(){const {data,error}=await db.from('travel_payments').select('amount,currency,method,status,transaction_reference,travel_registration_id').order('created_at',{ascending:false});if(error){$('#paymentSummary').textContent='Aucun paiement accessible.';return}const total=(data||[]).filter(x=>x.status==='confirme').reduce((s,x)=>s+Number(x.amount||0),0);$('#paymentSummary').innerHTML=`<div class="stats-grid"><div class="stat"><span>Paiements</span><strong>${data?.length||0}</strong></div><div class="stat"><span>Total confirmé</span><strong>${total.toLocaleString('fr-FR')} XOF</strong></div></div>`}
document.addEventListener('DOMContentLoaded',init);