const SUPABASE_URL='https://bhpscrmwsmcwmvapemxz.supabase.co';const SUPABASE_KEY='sb_publishable_lj2RFmTiDKIMr7K-suRbCA_yOuLekl9';let db,user,profile;
const $=s=>document.querySelector(s);const $$=s=>document.querySelectorAll(s);const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
async function init(){db=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);const {data:{user:u}}=await db.auth.getUser();user=u;if(!user){location.href='login.html';return}const {data:p,error}=await db.from('profiles').select('full_name,phone,role').eq('id',user.id).single();if(error||!p||!['admin','agent'].includes(p.role)){await db.auth.signOut();location.href='login.html';return}profile=p;$('#userInfo').textContent=`${p.full_name||user.email} · ${p.role==='admin'?'Administrateur':'Personnel'}`;if(p.role!=='admin'){$('#staffNav').style.display='none';$('#staff').innerHTML='<div class="panel"><h2>Accès restreint</h2><p>La gestion des comptes du personnel est réservée aux administrateurs.</p></div>';}setupNav();loadAll()}
function setupNav(){$$('nav button').forEach(btn=>btn.onclick=()=>{ $$('.view').forEach(v=>v.classList.remove('active'));$('#'+btn.dataset.view).classList.add('active');$('#pageTitle').textContent=btn.textContent;loadView(btn.dataset.view)});$('#logout').onclick=async()=>{await db.auth.signOut();location.href='login.html'};$('#refresh').onclick=loadAll;$('#staffForm')?.addEventListener('submit',createStaff)}
async function getRegs(){const {data,error}=await db.from('travel_registrations').select('*').order('created_at',{ascending:false});if(error){console.error(error);return []}return data||[]}
async function loadAll(){const r=await getRegs();renderStats(r);renderRecent(r);renderRegistrations(r);renderClients(r);renderStatsDetail(r);if(profile.role==='admin')loadStaff()}
async function loadView(v){if(v==='dashboard'||v==='registrations'||v==='clients'||v==='stats')return loadAll();if(v==='payments')loadPayments()}
function renderStats(r){$('#total').textContent=r.length;$('#newCount').textContent=r.filter(x=>x.status==='nouveau').length;$('#confirmed').textContent=r.filter(x=>x.status==='confirme').length;$('#cancelled').textContent=r.filter(x=>x.status==='annule').length}
function statusOptions(current){return ['nouveau','en_cours','confirme','annule'].map(s=>`<option ${s===current?'selected':''} value="${s}">${s.replace('_',' ')}</option>`).join('')}
function renderRegistrations(r){$('#registrationRows').innerHTML=r.map(x=>`<tr><td><strong>${esc(x.dossier_number)}</strong></td><td>${esc(x.full_name)}</td><td>${esc(x.service)}</td><td>${esc(x.phone)}</td><td>${esc(x.travel_date||'—')}</td><td><select class="status-select" data-id="${x.id}">${statusOptions(x.status)}</select></td><td><button class="small" data-detail="${x.id}">Voir</button></td></tr>`).join('')||'<tr><td colspan="7">Aucun dossier.</td></tr>';$$('.status-select').forEach(s=>s.onchange=async e=>{await db.from('travel_registrations').update({status:e.target.value}).eq('id',e.target.dataset.id);loadAll()})}
function renderRecent(r){$('#recent').innerHTML=r.slice(0,5).map(x=>`<div class="recent-row"><strong>${esc(x.dossier_number)}</strong><span>${esc(x.full_name)} · ${esc(x.service)}</span><span class="badge">${esc(x.status)}</span></div>`).join('')||'<p>Aucun dossier.</p>'}
function renderClients(r){$('#clientRows').innerHTML=r.map(x=>`<tr><td>${esc(x.full_name)}</td><td>${esc(x.phone)}</td><td>${esc(x.email||'—')}</td><td>${esc(x.service)}</td><td>${esc(x.dossier_number)}</td></tr>`).join('')||'<tr><td colspan="5">Aucun client.</td></tr>'}
function renderStatsDetail(r){$('#hajjCount').textContent=r.filter(x=>x.service==='hajj').length;$('#omraCount').textContent=r.filter(x=>x.service==='omra').length;$('#voyageCount').textContent=r.filter(x=>x.service==='voyage').length}
async function loadStaff(){const {data,error}=await db.from('profiles').select('full_name,phone,role,id').in('role',['admin','agent']).order('created_at',{ascending:false});if(error){$('#staffRows').innerHTML='<tr><td colspan="4">Impossible de charger le personnel.</td></tr>';return}$('#staffCount').textContent=(data||[]).length;$('#staffRows').innerHTML=(data||[]).map(x=>`<tr><td>${esc(x.full_name)}</td><td>Compte Supabase</td><td>${esc(x.phone||'—')}</td><td><span class="badge">${esc(x.role)}</span></td></tr>`).join('')||'<tr><td colspan="4">Aucun compte.</td></tr>'}
async function createStaff(e){e.preventDefault();if(profile.role!=='admin')return;const f=e.currentTarget,m=$('#staffMessage'),b=f.querySelector('button');b.disabled=true;b.textContent='Création...';const body={email:f.email.value.trim(),password:f.password.value,full_name:f.full_name.value.trim(),phone:f.phone.value.trim(),role:f.role.value};const {data:{session}}=await db.auth.getSession();const res=await fetch(`${SUPABASE_URL}/functions/v1/create-staff-user`,{method:'POST',headers:{Authorization:`Bearer ${session.access_token}`, 'Content-Type':'application/json'},body:JSON.stringify(body)});const out=await res.json();b.disabled=false;b.textContent='Créer le compte';if(!res.ok){m.textContent=out.error||'Création impossible';return}m.textContent='Compte créé avec succès.';f.reset();loadStaff()}
async function loadPayments(){const {data,error}=await db.from('travel_payments').select('amount,currency,method,status,transaction_reference,travel_registration_id').order('created_at',{ascending:false});if(error){$('#paymentSummary').textContent='Aucun paiement accessible.';return}const total=(data||[]).filter(x=>x.status==='confirme').reduce((s,x)=>s+Number(x.amount||0),0);$('#paymentSummary').innerHTML=`<div class="stats-grid"><div class="stat"><span>Paiements</span><strong>${data?.length||0}</strong></div><div class="stat"><span>Total confirmé</span><strong>${total.toLocaleString('fr-FR')} XOF</strong></div></div>`}
document.addEventListener('DOMContentLoaded',init);